# Anova

In [1]:
## Anova = variance between the groups/variance within the group
## F-Test --> for decision

In [2]:
import numpy as np
import pandas as pd

In [3]:
train_1 = np.random.randint(1, 10, 10)
print(train_1)
train_2 = np.random.randint(1, 10, 10)
print(train_2)
train_3 = np.random.randint(1, 10, 10)
print(train_3)

[8 7 6 6 2 5 8 4 9 5]
[7 7 8 2 3 6 4 3 9 1]
[3 1 9 1 4 6 9 2 4 2]


In [4]:
## Create a table
anova_df = pd.DataFrame({'Train_A': train_1, 'Train_B': train_2, 'Train_C': train_3})
anova_df

Train_A  Train_B  Train_C
0        8        7        3
1        7        7        1
2        6        8        9
3        6        2        1
4        2        3        4
5        5        6        6
6        8        4        9
7        4        3        2
8        9        9        4
9        5        1        2

In [5]:
## Anova = variance between the groups/variance within the group

In [6]:
## F_stat = MSbetween/MSwithin

In [7]:
## SS between, SSwithin
sample_count = 10

In [9]:
## Sum of each groups
anova_df.sum()

Train_A    60
Train_B    50
Train_C    41
dtype: int64

In [10]:
## Sum of squares/N
sum_sq_each_grp = anova_df.sum()**2/sample_count
sum_sq_each_grp

Train_A    360.0
Train_B    250.0
Train_C    168.1
dtype: float64

In [11]:
sum_sq = sum_sq_each_grp.sum()
sum_sq

778.1

In [14]:
## Sum of sum of square of each CGPA
sum_sum_sqr_cgpa = anova_df.applymap(lambda x: x**2).sum().sum()
sum_sum_sqr_cgpa

967

In [19]:
sum_sum_sqr_all = (anova_df.sum().sum()**2)/30
sum_sum_sqr_all

760.0333333333333

In [20]:
## Degree of freedom
dfbetween = 3-1
dfwithin = (10*3) - 3

In [21]:
# Sum of square within (SSwithin)
sswithin = sum_sum_sqr_cgpa - sum_sq
sswithin

188.89999999999998

In [23]:
## Sum of square between
ssbetween = sum_sq - sum_sum_sqr_all
ssbetween

18.06666666666672

In [24]:
## Mean sum of square between
msb = ssbetween/dfbetween
msb

9.03333333333336

In [25]:
## Mean sum of square within
msw = sswithin/dfwithin
msw

6.996296296296295

In [26]:
f_stat = msb/msw
f_stat

1.2911593435680295

In [27]:
from scipy.stats import f_oneway

f_oneway(train_1, train_2, train_3)

F_onewayResult(statistic=1.2911593435680255, pvalue=0.2913908851752782)

In [28]:
## Final decision --> Accept H0 --> All the means are equal

In [30]:
## Two way anova
df = pd.DataFrame({'Fertilizer': np.repeat(['A','B'], 15),
                   'Climate': np.repeat(['Winter','Summer'], 15),
                   'Height': np.random.randint(13,20,30)})

df

Fertilizer Climate  Height
0           A  Winter      19
1           A  Winter      17
2           A  Winter      19
3           A  Winter      14
4           A  Winter      13
5           A  Winter      16
6           A  Winter      15
7           A  Winter      14
8           A  Winter      15
9           A  Winter      17
10          A  Winter      16
11          A  Winter      19
12          A  Winter      17
13          A  Winter      14
14          A  Winter      18
15          B  Summer      13
16          B  Summer      19
17          B  Summer      16
18          B  Summer      19
19          B  Summer      18
20          B  Summer      14
21          B  Summer      14
22          B  Summer      13
23          B  Summer      15
24          B  Summer      16
25          B  Summer      15
26          B  Summer      14
27          B  Summer      17
28          B  Summer      19
29          B  Summer      16

In [31]:
from statsmodels.formula.api import ols
import statsmodels.api as sm

two_way_anova = ols('Height ~ C(Fertilizer) + C(Climate) + C(Fertilizer):C(Climate)', data=df).fit()
result = sm.stats.anova_lm(two_way_anova, type=2)

print(result)

                            df      sum_sq   mean_sq         F    PR(>F)
C(Fertilizer)              1.0    0.833333  0.833333  0.194229  0.662804
C(Climate)                 1.0    8.794941  8.794941  2.049875  0.163288
C(Fertilizer):C(Climate)   1.0    6.616239  6.616239  1.542076  0.224611
Residual                  28.0  120.133333  4.290476       NaN       NaN


In [ ]:
how can we decide no impact pls explain once
## >0.05 ---> Avg is same

In [ ]:
## two medicine --> weight
## --> 3 -->avg weight --> A-78, B-79, C-77 --> 0.876

# Z-Test

In [ ]:
## Compare two sample mean >> 30 samples

In [35]:
from random import sample

In [36]:
## Average height of indian adult male is 165 cm

## H0 = "Avg height is 165"
## H1 = "Avg height is not 165"

sample_heights = sample(range(100, 200), 80)
print(sample_heights)

[153, 182, 119, 156, 168, 111, 127, 174, 101, 163, 108, 152, 140, 166, 199, 103, 189, 139, 133, 181, 169, 198, 109, 180, 175, 132, 137, 122, 157, 158, 186, 115, 141, 136, 106, 173, 172, 162, 114, 125, 184, 107, 120, 197, 105, 183, 138, 131, 177, 159, 128, 142, 164, 117, 148, 188, 185, 104, 100, 135, 116, 118, 102, 155, 134, 146, 165, 191, 193, 160, 150, 195, 171, 170, 113, 176, 190, 112, 130, 129]


In [38]:
from statsmodels.stats.weightstats import ztest

ztest(sample_heights, value=165)

(-5.061278798942744, 4.164537124818011e-07)

In [ ]:
### p <<<o.o5 --> Reject H0 --> Avg height is not 165

# Two sample z test

In [40]:
school_a = sample(range(20, 100), 80)
print(school_a)
school_b = sample(range(20, 100), 80)
print(school_b)

[59, 43, 29, 72, 67, 90, 36, 70, 95, 93, 66, 57, 62, 89, 74, 81, 41, 98, 68, 75, 26, 39, 94, 42, 47, 99, 92, 23, 35, 24, 73, 44, 48, 51, 54, 31, 49, 21, 60, 55, 25, 40, 77, 38, 46, 79, 86, 82, 87, 83, 50, 30, 88, 63, 78, 28, 91, 27, 97, 52, 58, 45, 80, 65, 34, 64, 71, 33, 76, 61, 85, 32, 53, 96, 69, 20, 84, 22, 37, 56]
[83, 91, 68, 76, 90, 81, 72, 24, 43, 80, 92, 50, 96, 45, 34, 41, 52, 99, 95, 29, 61, 46, 60, 23, 79, 55, 85, 86, 44, 67, 65, 78, 71, 54, 97, 20, 31, 21, 35, 58, 69, 89, 82, 88, 40, 51, 77, 87, 98, 30, 75, 32, 57, 63, 26, 66, 39, 28, 38, 25, 53, 74, 84, 94, 70, 93, 22, 27, 42, 47, 56, 73, 64, 62, 48, 49, 59, 33, 37, 36]


In [41]:
ztest(school_a, school_b)

(0.0, 1.0)

In [42]:
## conclusion --> Accept h0 --> "Avg marks are same"

# Z Test for proportion

# One sample

In [43]:
p = 0.35

In [45]:
sample_purchase_amount_for_women = sample(range(9000, 11000), 200)
print(sample_purchase_amount_for_women)

[10490, 10480, 9236, 9819, 9740, 10430, 9036, 10603, 9944, 9630, 10953, 9937, 10280, 9259, 9412, 10631, 10788, 10815, 10827, 9100, 10607, 9831, 10356, 10331, 9098, 10848, 10302, 10875, 10326, 10558, 9140, 9974, 10442, 9078, 10542, 9548, 9512, 9130, 10243, 10549, 9314, 9306, 9043, 9964, 9766, 9409, 10509, 10889, 10739, 10709, 9461, 9454, 9239, 10412, 10487, 10422, 10453, 10649, 10127, 10071, 10839, 9169, 9253, 10679, 10977, 10592, 9782, 10007, 9421, 9345, 10500, 10306, 10704, 10911, 9560, 9304, 10031, 10986, 10872, 9495, 10029, 10865, 10538, 9712, 9101, 10519, 10510, 10880, 9697, 9521, 9732, 9240, 10195, 10042, 9511, 10292, 9494, 9079, 9841, 10263, 10402, 9206, 9334, 9339, 9048, 9827, 10385, 10983, 9405, 9067, 10107, 10353, 9464, 10171, 10497, 10535, 9195, 9806, 9196, 9116, 10148, 9038, 10531, 10240, 9228, 9034, 9439, 9814, 9175, 9354, 9741, 9489, 9446, 10266, 10478, 10992, 10149, 10854, 10142, 10351, 10720, 9331, 10069, 9394, 9233, 10617, 9997, 10960, 10382, 9780, 9645, 9840, 10802, 97

In [46]:
### from 200 samples, I'm drawing a coclusion about poplation that,
### 35% of womens have a purchase amount more than 10000 or not

## H0 = proprtion is 35%
## H1 = proportion is not 35%

In [47]:
count_of_women_have_purchase_amount_greater_than_10000 = len([i for i in sample_purchase_amount_for_women if i>10000])
count_of_women_have_purchase_amount_greater_than_10000

101

In [48]:
from statsmodels.stats.proportion import proportions_ztest

proportions_ztest(count=count_of_women_have_purchase_amount_greater_than_10000, nobs = 200, value=0.35)

(4.384281262900366, 1.1636934315532383e-05)

# Two sample

In [49]:
sample_purchase_amt_18_25 = sample(range(3000, 8000), 200)
print(sample_purchase_amt_18_25)
sample_purchase_amt_26_35 = sample(range(4000, 10000), 200)
print(sample_purchase_amt_26_35)

[7428, 5670, 4528, 6256, 5081, 5032, 4218, 5015, 5519, 7518, 5526, 4882, 3935, 6318, 7130, 3206, 5140, 6883, 4583, 5042, 7559, 3634, 4080, 7940, 3850, 3878, 7552, 4862, 5462, 3961, 3158, 6611, 3550, 6782, 5973, 3080, 3647, 3618, 3608, 6149, 5566, 6021, 6570, 4697, 7261, 3073, 6767, 5934, 3772, 4576, 5426, 6336, 3676, 5685, 5558, 7735, 7933, 5570, 5037, 5629, 7747, 7074, 5155, 4046, 5701, 6709, 3161, 3013, 5872, 5664, 7777, 4326, 6181, 5028, 7136, 3622, 6444, 7168, 7020, 5367, 7652, 6164, 6214, 4807, 7803, 7474, 6679, 4783, 4905, 5871, 6483, 5671, 7982, 3381, 5361, 5170, 4500, 7647, 6855, 3886, 4782, 3699, 6794, 6881, 5753, 3661, 7209, 4065, 6309, 3754, 3071, 4469, 7521, 6666, 7665, 4943, 5084, 5373, 6643, 4271, 7205, 5731, 3088, 5709, 4168, 7828, 7266, 6032, 5991, 3059, 5435, 4535, 7377, 4683, 5318, 5277, 5306, 5770, 7615, 6205, 3868, 7595, 5887, 6504, 5362, 5879, 5949, 5987, 5999, 5008, 5297, 6633, 7510, 7862, 6914, 6539, 4004, 5585, 7190, 7953, 7813, 5393, 6621, 4199, 5984, 7504, 647

In [50]:
## From the 200 samples, I'm drawing the conclusion about population that, 
## age groups 18 to 25 and 26 to 35 have same proportion in purchase amount > 5000

H0 = "proprtion are same"
H1 = "Proprtion is not same"

In [52]:
count_of_customers_have_grt_5000_18_25 = len([i for i in sample_purchase_amt_18_25 if i>5000])
count_of_customers_have_grt_5000_26_35 = len([i for i in sample_purchase_amt_26_35 if i>5000])

print(count_of_customers_have_grt_5000_18_25, count_of_customers_have_grt_5000_26_35)

139 172


In [54]:
139/200

0.695

In [55]:
172/200

0.86

In [53]:
proportions_ztest(count=[count_of_customers_have_grt_5000_18_25, count_of_customers_have_grt_5000_26_35],
                  nobs=[200, 200])

(-3.9670597138462105, 7.276476622318882e-05)

In [ ]:
## Final conclusion --> Reject H0 since p<<0.05 --> significant difference in the purchase pattern for two age groups

# Chi-Sqaure Test

In [56]:
H0 = 'No relation between Gender and Fav sports'
H0 = 'There is a relation exists between Gender and Fav sports'

In [59]:
import random

chi_df = pd.DataFrame({"Gender": random.choices(['Female', 'Male'], k=10),
                       'Fav-Sports': random.choices(['Football', 'Badminton'], k=10)})

chi_df

Gender Fav-Sports
0  Female  Badminton
1  Female   Football
2  Female  Badminton
3    Male   Football
4    Male   Football
5  Female   Football
6  Female   Football
7    Male  Badminton
8    Male   Football
9    Male   Football

In [60]:
## Male -- Badminton --> 1
## FeMale -- Badminton --> 2
## Male -- Football --> 4
## FeMale -- Football --> 3

chi_df

Gender Fav-Sports
0  Female  Badminton
1  Female   Football
2  Female  Badminton
3    Male   Football
4    Male   Football
5  Female   Football
6  Female   Football
7    Male  Badminton
8    Male   Football
9    Male   Football

In [62]:
cross_tab_data = pd.crosstab(chi_df['Gender'], chi_df['Fav-Sports'])
cross_tab_data

Fav-Sports  Badminton  Football
Gender                         
Female              2         3
Male                1         4

In [63]:
## Chi_val = (Observed-Expected)**2/Expected
## Expected Val = Row*col/N

In [64]:
from scipy.stats import chi2_contingency

chi2_contingency(cross_tab_data)

(0.0,
 1.0,
 1,
 array([[1.5, 3.5],
        [1.5, 3.5]]))

In [ ]:
## Final conclusion --> Accept H0 --> No relation