In [2]:
import numpy as np

In [45]:
# slicing -> (start=0, end-1, step=1)
# If step is +ve, default start = 0
# If step is -ve, default start = -1

nums = np.array([10, 20, 30, 40, 50])
# print(nums)
# print(nums[0], nums[1], nums[2], nums[3], nums[4], nums[5])
# print(nums[-1], nums[-2], nums[-3], nums[-4], nums[-5], nums[-6])

# print(nums[0:4])
# print(nums[4:1])
# print(nums[:3])
# print(nums[1:])
# print(nums[1:10])
# print(nums[:])
# print(nums[0:4:2])
# print(nums[1::2])
# print(nums[0::2])

# print(nums[-3:-1])
# print(nums[-2:-5])
# print(nums[-2:-5:-1])
# print(nums[-5:-1:2])
# print(nums[:1:-1])
# print(nums[4:-3])
# print(nums[4:1:-1])
# print(nums[:2:-1])
# print(nums[-1:0:2])
# print(nums[::1])
# print(nums[::-1])

[40 50]


In [5]:
# 2d array -> [rows, cols] -> [(start=0, end-1, step=1), (start=0, end-1, step=1)]
nums = np.array([
    [11, 12, 13, 14, 15, 16, 17, 18],
    [21, 22, 23, 24, 25, 26, 27, 28]
])

# print(nums)
# print(nums[0], nums[1])
# print(nums[-1], nums[-2])

# <------ multiple rows ------>
# print(nums[:])
# print(nums[:1])
# print(nums[0:])
# print(nums[1::2])
# print(nums[-1:])
# print(nums[-1::-1])

# <------- one row and multiple cols ------>
# print(nums[0, 1:5])
# print(nums[-2, 2:6])
# print(nums[-1, -6:-2:-1])
# print(nums[-1, -6:-2:1])
# print(nums[-2, :-7:])
# print(nums[-1, 2:-6:-1])
# print(nums[-1, 2:-6:1])

# <------ multiple rows and multiple cols ------->
# print(nums[:, 2:7])
# print(nums[:1, -6:4])
# print(nums[::-1, 2:-3])
# print(nums[:2:, 1])
# print(nums[0:, -6:4])

# print(nums[:, 5])

[[21 22 23 24 25 26 27 28]]
[[21 22 23 24 25 26 27 28]
 [11 12 13 14 15 16 17 18]]


In [86]:
# change the data using slicing

nums = np.array([
    [11, 12, 13, 14, 15, 16, 17, 18],
    [21, 22, 23, 24, 25, 26, 27, 28]
])

# nums[0, 5] = 100
# print(nums)

# 12, 15, 18 -> 100
nums[-2, -7:10:3] = 100
print(nums)

[[ 11 100  13  14 100  16  17 100]
 [ 21  22  23  24  25  26  27  28]]


In [7]:
# reshaping the array
nums = np.array([1, 2, 3, 4, 5, 6])
# print(nums, nums.shape)
# print(nums.reshape(2,3))
# print(nums.reshape(3,2))
# print(nums.reshape(1, 6))
# print(nums.reshape(2, 4)) # value error

# 2d array
nums = np.array([
    [1, 2, 3, 4],
    [4, 5, 6, 7],
    [6, 7, 8, 9]
])

# print(np.reshape(nums, (4,3)))

# print(nums.shape)
# print(nums.reshape(1, 12))
# print(nums.reshape(2, 6))
# print(nums.reshape(4, 3))
# print(nums.reshape(6, 2))
# print(nums.reshape(12, 1))

[[1 2 3]
 [4 4 5]
 [6 7 6]
 [7 8 9]]


In [9]:
# stacking the data
# horizontal stack
n1 = np.array([1, 2, 3, 4])
n2 = np.array([5, 6, 7, 8])

# print(np.hstack([n1, n2, n1, n1, n2]))

# vertical stack
print(np.vstack([n1, n2, n1, n1, n2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]


In [19]:
# splitting the data -> vertical splitting
nums = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],

    [9, 10, 11, 12],
    [1,  2,  3,  4],
    
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

# print(nums.shape)

# <------- uniform splitting ------->
from pprint import pprint
# pprint(np.vsplit(nums, 3))
# pprint(np.vsplit(nums, 3)[0])
# pprint(np.vsplit(nums, 3)[1])
# pprint(np.vsplit(nums, 3)[2])
# pprint(np.vsplit(nums, 3)[3]) # index error

# pprint(np.vsplit(nums, 4))

# pprint(np.vsplit(nums, 2))
# pprint(np.vsplit(nums, 2)[0])
# pprint(np.vsplit(nums, 2)[1])


# custom cut
pprint(np.vsplit(nums, [2,4]))
# pprint(np.vsplit(nums, [1, 3])[0])
# pprint(np.vsplit(nums, [1, 3])[1])
# pprint(np.vsplit(nums, [1, 3])[2])

# pprint(np.vsplit(nums, [0, 2, 4]))
# pprint(np.vsplit(nums, [0, 2, 4])[0])
# pprint(np.vsplit(nums, [0, 2, 4])[1])
# pprint(np.vsplit(nums, [0, 2, 4])[2])
# pprint(np.vsplit(nums, [0, 2, 4])[3])

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4]]),
 array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])]


In [157]:
# nums = np.array([1, 2, 3, 4])
# print(nums[0], nums[-1])
# nums[0], nums[-1], nums[-2], nums[-3] = nums[-1], nums[0], nums[1], nums[2]
# print(nums)

1 4
[4 3 2 1]


In [173]:
# horizontal splitting
nums = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

# uniform splitting
# pprint(np.hsplit(nums, 2))
# pprint(np.hsplit(nums, 2)[0])
# pprint(np.hsplit(nums, 2)[1])
# pprint(np.hsplit(nums, 3))

# custom 
# pprint(np.hsplit(nums, (2, 3)))
# pprint(np.hsplit(nums, (2, 3))[0])
# pprint(np.hsplit(nums, (2, 3))[1])
# pprint(np.hsplit(nums, (2, 3))[2])

pprint(np.hsplit(nums, (0, 2, 4)))

[array([], shape=(3, 0), dtype=int64),
 array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]),
 array([[ 3,  4],
       [ 7,  8],
       [11, 12]]),
 array([], shape=(3, 0), dtype=int64)]


In [188]:
# comparison operators -> boolean
nums = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

# print(nums > 5)
# print(nums >= 5)
# print(nums < 5)
# print(nums <= 5)
# print(nums == 5)
# print(nums != 5)

# filtering the data -> array[condition]
# print(nums[nums > 5])
# print(nums[nums != 5])

# even nums
even_nos = (nums % 2 == 0)
odd_nos = (nums % 2 != 0)
print(even_nos)
print(nums[even_nos])
print(nums[odd_nos])

[[False  True False  True]
 [False  True False  True]]
[2 4 6 8]
[1 3 5 7]


In [190]:
# linear alg
# determinant
nums = np.array([
    [1, 2],
    [3, 4]
])
# print(np.linalg.det(nums))

# inverse of a matrix -> [Adj(nums)/det(nums)] -> adj(nums) = |d -b|
#                                                             |-c a|
print(np.linalg.inv(nums))
 

[[-2.   1. ]
 [ 1.5 -0.5]]


In [196]:
# transpose
nums = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(np.transpose(nums))

[[1]
 [2]
 [3]
 [4]]


In [194]:
# sorting
nums = np.array([
    [33, 87, 22, 59],
    [76, 60, 1, 74],
    [69, 6, 57, 90]
])

# print(np.sort(nums))
# print(np.sort(nums, axis=1)) # same as above
# print(np.sort(nums, axis=0))

[[33  6  1 59]
 [69 60 22 74]
 [76 87 57 90]]


In [20]:
# broadcasting
a = np.array([
    [33, 87, 22, 59],
    [76, 60, 1, 74],
    [69, 6, 57, 90]
])

# b = np.array([1, 2, 3, 4])
b = np.array([
    [1],
    [2],
    [3]
])

print(a + b)

[[34 88 23 60]
 [78 62  3 76]
 [72  9 60 93]]


In [209]:
# stats
nums = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 100]
])

print(np.mean(nums))
print(np.median(nums))
print(np.std(nums))
print(np.var(nums)) # -> var = (std dev) ** 2

13.833333333333334
6.5
26.15604880116431
684.138888888889
