In [1]:
# variables, datatypes, collections, loops, conditional statements, functions, modules
# OOPs -> class, object, property, methods, polymorphism, encapsulation, inheritance and abstraction

In [2]:
# NUMPY -> numerical python
# collect the data(product -> DB) -> Preprocessing the data (Numpy, Pandas)

In [5]:
# N dimensions
heros = ['srk', 'kamal', 'surya'] # 1d

# hero-director pair # 2d
pairs = [
    ['srk', 'atlee', 'nayan'],
    ['kamal', 'lokesh', 'kajal'],
    ['surya', 'ssr', 'anushka']
]

SyntaxError: invalid syntax (1976035388.py, line 10)

In [4]:
# pip install numpy
# conda install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy
print(numpy.__version__)

1.24.3


In [8]:
# numpy -> only datatype -> typed array
# nums = [10, True, 'vasanth', 10.5]
# print(nums)

import numpy as np

nums = np.array([10, True, 'vasanth', 10.5])
print(nums)

['10' 'True' 'vasanth' '10.5']


In [12]:
nums_list = [1, 2, 3, 4]
# print(nums_list)

nums = np.array(nums_list)
print(nums, type(nums)) # n dimensional array

[1 2 3 4] <class 'numpy.ndarray'>


In [68]:
nums = np.array([1, 2, 3], dtype='int64')
# print(nums, nums[0], nums[1], nums[2])
# print(nums[-1], nums[-2], nums[-3], nums[-4])

# print(type(nums), nums.dtype) # int64 -> 8 bytes, int32 -> 4 bytes
# print(nums.itemsize, 'bytes')
# print(nums.shape)
# print(nums.ndim) # n dimension
# print(len(nums), nums.size) # no of elements
# print(sum(nums))
print(np.sum(nums))

6


In [69]:
# 2d
nums = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [5, 6, 7, 8]
])

# print(nums, type(nums), nums.dtype)
# print(nums[0], nums[1])
# print(nums[0][0], nums[0][1], nums[0][2], nums[0][3])
# print(nums[1][0], nums[1][1], nums[1][2], nums[1][3])
# print(nums[0, 0], nums[0, 1], nums[1, 2])

# print(nums.itemsize, 'bytes')
# print(nums.shape) # (3, 4)
# print(nums.ndim) # 2d data
# print(len(nums), len(nums[0]), nums.size) # len -> no of sub elements, size -> total no of elements
# print(sum(nums))
# print(np.sum(nums))

[11 14 17 20]
62


In [102]:
# 3d

nums = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [4, 5, 6],
        [4, 5, 6]
    ],
    [
        [5, 16, 7],
        [7, 8, 9]
    ]
])

# print(nums, type(nums), nums.dtype)
# print(nums.shape) # (3, 2, 3)
# print(nums.itemsize) # 8 
# print(nums.ndim)

from pprint import pprint # pretty print
# pprint(nums[0])
# pprint(nums[1])
# pprint(nums[2])

# print(nums[0, 0], nums[0, 1])
# print(nums[1, 0], nums[1, 1])
# print(nums[2, 0], nums[2, 1])

# print(nums[0, 0, 0], nums[0, 0, 1])

# 16
# print(nums[2, 0, 1])

# print(np.sum(nums))
# print(nums.size, len(nums), len(nums[0]), len(nums[0, 0]))

# total memory space
# print(nums.size * nums.itemsize, 'bytes')

144 bytes


In [126]:
# zero matrix -> float
# nums = np.zeros((5, 5), dtype='int64')
# print(nums)

# ones matrix -> float
# nums = np.ones((3, 3), dtype='int64')
# print(nums)

# identity matrix
# nums = np.identity(4, dtype='int64')
# print(nums)

# full matrix
# nums = np.full((4, 3), 5)
# print(nums)

# full_like
# db data
nums = np.array([
    [1, 2, 3],
    [3, 4, 4],
    [3, 4, 4],
])

default = np.full_like(nums, 0)
print(default)

[]


In [125]:
data = np.array([
    [1, 2, 3, 4],
    [1, 2, 3, 4],
])

# print(data.ndim) # n dim

# ndmin -> nd minimum
# nums = np.array(data, ndmin=10)
# print(nums, nums.ndim)

nums = np.array(data, ndmin=1)
print(nums)

[[1 2 3 4]
 [1 2 3 4]]


In [136]:
# list_nums = [1, 2, 3, 4]
# print(list_nums + 5)

# arithmetic operations
# nums = np.array([1, 2, 3, 4])
# print(nums + 5)
# print(nums - 5)
# print(nums * 5)
# print(nums / 5)
# print(nums // 5)
# print(nums % 5)
# print(nums ** 5)

[6 7 8 9]
[-4 -3 -2 -1]
[ 5 10 15 20]
[0.2 0.4 0.6 0.8]
[0 0 0 0]
[1 2 3 4]
[   1   32  243 1024]


In [146]:
num1 = np.array([
    [1, 2],
    [3, 4]
])

num2 = np.array([
    [1, 2],
    [3, 4]
])

# print(num1 + num2)
# print(num1 - num2)
# print(num1 * num2)
# print(num1 / num2)
# print(num1 // num2)
# print(num1 ** num2)

# dot product
# print(np.dot(num1, num2))

# cross product
n1 = np.array([10, 20, 30])
n2 = np.array([4, 9, 12])

print(np.cross(n1, n2))

[-30   0  10]


In [156]:
# repeat
nums = np.array([1, 2, 3])
# print(np.repeat(nums, 3))
# print(np.repeat(nums, 3, axis=0))
# print(np.repeat(nums, 3, axis=1)) # axis error

nums = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
# print(np.repeat(nums, 3))
# print(np.repeat(nums, 3, axis=0))
# print(np.repeat(nums, 3, axis=1))

In [160]:
nums = [1, 2, 3]
copy = nums
print(nums, copy)
copy[0] = 10
print(nums, copy)

[1, 2, 3] [1, 2, 3]
[1, 2, 3] [10, 2, 3]


In [ ]:
# list vs array
# list -> size, data type(object), obj value, referrence count, 
# array -> less memory and continuous memory 

In [171]:
# random data
# nums = np.random.randint(low=10, high=100, size=(3, 3))
# nums = np.random.uniform(low=10, high=100, size=(5, 5))
# print(nums)

[[53 34 14]
 [31 66 84]
 [26 88 83]]


In [181]:
# speed test

from timeit import default_timer as timer

a = np.random.random(1000) # 0 - 1
b = np.random.random(1000)

list_a = list(a)
list_b = list(b)

# dot product
def find_dot():
    return np.dot(a, b)

# logic of dot product using list
def find_product():
    dot = 0
    for i in range(len(list_a)):
        dot += list_a[i] * list_b[i]
    return dot


start = timer()
for i in range(100000):
    find_product()
end = timer()
print('list -> ', end - start)

start = timer()
for i in range(100000):
    find_dot()
end = timer()
print('numpy -> ', end - start)

list ->  6.975256167002954
numpy ->  0.09373125003185123
