In [23]:
import numpy as np
import pprint
pp = pprint.PrettyPrinter(indent=2)
# 17) Given two vectors A and B, find the cross product between the two vectors. A = numpy.array([[4],[12],[29]]) B = numpy.array([[13],[21],[4]])
# array([[-560 360 -71]])
# array([[-561 360 -72]])
# array([[-555 361 -72]])
# array([[-561 361 -72]])


A = np.array([
    [4],[12],[29]
]) 
B = np.array([
    [13],[21],[4]
])

A = np.array([
    4,12,29
]) 
B = np.array([
    13,21,4
])
print(A.ndim)
print(B.ndim)
np.cross(A,B)



1
1


array([-561,  361,  -72])

In [9]:

A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25]) 
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])
np.corrcoef(A, B)

array([[1., 1.],
       [1., 1.]])

In [16]:
# 19) Create a nested numpy array from a given dictionary data. sample = {1: [1,2], 2: [[1],[2]], 3: [[1,2], [3,4], [4,5]], 4: [1], 5: [1,2,3,4,5]}


# array([[1, list([1, 2])], [2, list([[1], [2]])], [3, list([[1, 2], [3, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 10, 5])]], dtype=object)
# array([[1, list([1, 2])], [2, list([[1], [2]])], [3, list([[1, 2], [1, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 4, 5])]], dtype=object)
# array([[1, list([1, 1])], [2, list([[1], [2]])], [3, list([[1, 2], [3, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 4, 5])]], dtype=object)
# array([[1, list([1, 2])], [2, list([[1], [2]])], [3, list([[1, 2], [3, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 4, 5])]], dtype=object)

sample = {
    1: [1,2], 
    2: [[1],[2]], 
    3: [[1,2], [3,4], [4,5]], 
    4: [1], 5: [1,2,3,4,5]
}
nested_arry = []
for k, v in sample.items():
    nested_arry.append([k, v])

nested_arry


[[1, [1, 2]],
 [2, [[1], [2]]],
 [3, [[1, 2], [3, 4], [4, 5]]],
 [4, [1]],
 [5, [1, 2, 3, 4, 5]]]

In [29]:
# 20) A 2-dimensional array with 3 rows and 3 columns containing random numbers from 1 to 9 is given 
# as - arr1= np.array([[3,2,1],[6,4,5],[8,7,9]]) 
# Find the difference between the maximum element across the columns and the minimum element across the rows.
# [7 3 2]
# [8 3 2]
# [7 1 2]
# [7 3 1]

arr1= np.array([
    [3,2,1],[6,4,5],[8,7,9]
    ])
arr = [1,2,3,4, [1,2], {}]
print(arr)
print(len(arr))



[1, 2, 3, 4, [1, 2], {}]
6


In [43]:
List =[3,9,12,15] 
a=(x**3 for x in List)
# print(list(a))
print(a)
print(next(a))
print(next(a))
print(next(a))
print(next(a))
# print(next(a))



<generator object <genexpr> at 0x117a9c3c0>
27
729
1728
3375


StopIteration: 

In [48]:
arr=np.array( [ [6,9,12] , [8,3,7] , [9,8,0] ] )
np.sum(arr, axis=1)

array([27, 18, 17])

In [55]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
np.column_stack([array1, array2])

# np.column_stack(array1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])