In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, r2_score
import seaborn as sns

In [9]:
data = pd.read_csv('./Files/wine.csv')

In [7]:
data.head()

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

In [57]:
data.isnull().sum()

Wine                    0
Alcohol                 0
Malic.acid              0
Ash                     0
Acl                     0
Mg                      0
Phenols                 0
Flavanoids              0
Nonflavanoid.phenols    0
Proanth                 0
Color.int               0
Hue                     0
OD                      0
Proline                 0
dtype: int64

In [58]:
data['Wine'].value_counts()

Wine
2    71
1    59
3    48
Name: count, dtype: int64

In [59]:
x, y = data.iloc[:, 0:12], data.iloc[:,-1]

In [60]:
x

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0       1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1       1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2       1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3       1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4       1    13.24        2.59  2.87  21.0  118     2.80        2.69   
..    ...      ...         ...   ...   ...  ...      ...         ...   
173     3    13.71        5.65  2.45  20.5   95     1.68        0.61   
174     3    13.40        3.91  2.48  23.0  102     1.80        0.75   
175     3    13.27        4.28  2.26  20.0  120     1.59        0.69   
176     3    13.17        2.59  2.37  20.0  120     1.65        0.68   
177     3    14.13        4.10  2.74  24.5   96     2.05        0.76   

     Nonflavanoid.phenols  Proanth  Color.int   Hue  
0                    0.28     2.29       5.64  1.04  
1                    0.26     1.28       4.38  1.05  
2                    0.30     2.81       5.68  1.03  
3                    0.24     2.18       7.80  0.86  
4                    0.39     1.82       4.32  1.04  
..                    ...      ...        ...   ...  
173                  0.52     1.06       7.70  0.64  
174                  0.43     1.41       7.30  0.70  
175                  0.43     1.35      10.20  0.59  
176                  0.53     1.46       9.30  0.60  
177                  0.56     1.35       9.20  0.61  

[178 rows x 12 columns]

In [61]:
y

0      1065
1      1050
2      1185
3      1480
4       735
       ... 
173     740
174     750
175     835
176     840
177     560
Name: Proline, Length: 178, dtype: int64

In [62]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.30)

In [63]:
x_train

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
122     2    12.42        4.43  2.73  26.5  102     2.20        2.13   
111     2    12.52        2.43  2.17  21.0   88     2.55        2.27   
70      2    12.29        1.61  2.21  20.4  103     1.10        1.02   
37      1    13.05        1.65  2.55  18.0   98     2.45        2.43   
48      1    14.10        2.02  2.40  18.8  103     2.75        2.92   
..    ...      ...         ...   ...   ...  ...      ...         ...   
84      2    11.84        0.89  2.58  18.0   94     2.20        2.21   
67      2    12.37        1.17  1.92  19.6   78     2.11        2.00   
169     3    13.40        4.60  2.86  25.0  112     1.98        0.96   
140     3    12.93        2.81  2.70  21.0   96     1.54        0.50   
14      1    14.38        1.87  2.38  12.0  102     3.30        3.64   

     Nonflavanoid.phenols  Proanth  Color.int    Hue  
122                  0.43     1.71       2.08  0.920  
111                  0.26     1.22       2.00  0.900  
70                   0.37     1.46       3.05  0.906  
37                   0.29     1.44       4.25  1.120  
48                   0.32     2.38       6.20  1.070  
..                    ...      ...        ...    ...  
84                   0.22     2.35       3.05  0.790  
67                   0.27     1.04       4.68  1.120  
169                  0.27     1.11       8.50  0.670  
140                  0.53     0.75       4.60  0.770  
14                   0.29     2.96       7.50  1.200  

[124 rows x 12 columns]

In [64]:
x_test

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
101     2    12.60        1.34  1.90  18.5   88     1.45        1.36   
12      1    13.75        1.73  2.41  16.0   89     2.60        2.76   
175     3    13.27        4.28  2.26  20.0  120     1.59        0.69   
154     3    12.58        1.29  2.10  20.0  103     1.48        0.58   
147     3    12.87        4.61  2.48  21.5   86     1.70        0.65   
61      2    12.64        1.36  2.02  16.8  100     2.02        1.41   
105     2    12.42        2.55  2.27  22.0   90     1.68        1.84   
63      2    12.37        1.13  2.16  19.0   87     3.50        3.10   
150     3    13.50        3.12  2.62  24.0  123     1.40        1.57   
133     3    12.70        3.55  2.36  21.5  106     1.70        1.20   
88      2    11.64        2.06  2.46  21.6   84     1.95        1.69   
128     2    12.37        1.63  2.30  24.5   88     2.22        2.45   
36      1    13.28        1.64  2.84  15.5  110     2.60        2.68   
30      1    13.73        1.50  2.70  22.5  101     3.00        3.25   
130     3    12.86        1.35  2.32  18.0  122     1.51        1.25   
79      2    12.70        3.87  2.40  23.0  101     2.83        2.55   
87      2    11.65        1.67  2.62  26.0   88     1.92        1.61   
100     2    12.08        2.08  1.70  17.5   97     2.23        2.17   
53      1    13.77        1.90  2.68  17.1  115     3.00        2.79   
77      2    11.84        2.89  2.23  18.0  112     1.72        1.32   
126     2    12.43        1.53  2.29  21.5   86     2.74        3.15   
156     3    13.84        4.12  2.38  19.5   89     1.80        0.83   
161     3    13.69        3.26  2.54  20.0  107     1.83        0.56   
41      1    13.41        3.84  2.12  18.8   90     2.45        2.68   
141     3    13.36        2.56  2.35  20.0   89     1.40        0.50   
33      1    13.76        1.53  2.70  19.5  132     2.95        2.74   
95      2    12.47        1.52  2.20  19.0  162     2.50        2.27   
26      1    13.39        1.77  2.62  16.1   93     2.85        2.94   
85      2    12.67        0.98  2.24  18.0   99     2.20        1.94   
129     2    12.04        4.30  2.38  22.0   80     2.10        1.75   
47      1    13.90        1.68  2.12  16.0  101     3.10        3.39   
6       1    14.39        1.87  2.45  14.6   96     2.50        2.52   
132     3    12.81        2.31  2.40  24.0   98     1.15        1.09   
167     3    12.82        3.37  2.30  19.5   88     1.48        0.66   
4       1    13.24        2.59  2.87  21.0  118     2.80        2.69   
55      1    13.56        1.73  2.46  20.5  116     2.96        2.78   
52      1    13.82        1.75  2.42  14.0  111     3.88        3.74   
134     3    12.51        1.24  2.25  17.5   85     2.00        0.58   
42      1    13.88        1.89  2.59  15.0  101     3.25        3.56   
158     3    14.34        1.68  2.70  25.0   98     2.80        1.31   
115     2    11.03        1.51  2.20  21.5   85     2.46        2.17   
151     3    12.79        2.67  2.48  22.0  112     1.48        1.36   
113     2    11.41        0.74  2.50  21.0   88     2.48        2.01   
2       1    13.16        2.36  2.67  18.6  101     2.80        3.24   
91      2    12.00        1.51  2.42  22.0   86     1.45        1.25   
119     2    12.00        3.43  2.00  19.0   87     2.00        1.64   
46      1    14.38        3.59  2.28  16.0  102     3.25        3.17   
96      2    11.81        2.12  2.74  21.5  134     1.60        0.99   
144     3    12.25        3.88  2.20  18.5  112     1.38        0.78   
93      2    12.29        2.83  2.22  18.0   88     2.45        2.25   
142     3    13.52        3.17  2.72  23.5   97     1.55        0.52   
65      2    12.37        1.21  2.56  18.1   98     2.42        2.65   
138     3    13.49        3.59  2.19  19.5   88     1.62        0.48   
73      2    12.99        1.67  2.60  30.0  139     3.30        2.89   

     Nonflavanoid.phenols  Proanth  Color.in

In [65]:
y_train

122     365
111     325
70      870
37     1105
48     1060
       ... 
84      520
67      510
169     630
140     600
14     1547
Name: Proline, Length: 124, dtype: int64

In [66]:
y_test

101     562
12     1320
175     835
154     640
147     625
61      450
105     315
63      420
150     500
133     600
88      680
128     342
36      880
30     1285
130     630
79      463
87      562
100     710
53     1375
77      500
126     352
156     480
161     680
41     1035
141     780
33     1235
95      937
26     1195
85      450
129     580
47      985
6      1290
132     560
167     685
4       735
55     1120
52     1190
134     650
42     1095
158     660
115     407
151     480
113     434
2      1185
91      450
119     564
46     1065
96      625
144     855
93      290
142     520
65      678
138     580
73      985
Name: Proline, dtype: int64

In [67]:
clf = LinearRegression()
clf.fit(x_train, y_train)

LinearRegression()

In [68]:
y_pred = clf.predict(x_test)

In [69]:
y_pred

array([ 509.00271852, 1100.83052078,  774.65870031,  578.4824732 ,
        575.36978445,  756.45175375,  466.24286549,  608.80141834,
        607.49870277,  389.90901472,  511.27802881,  393.4932414 ,
       1113.35171877, 1081.11472561,  406.15642887,  520.22393707,
        524.21544001,  491.07275688, 1218.64404955,  556.99030766,
        462.83710034,  727.38587951,  639.53176   ,  874.76891652,
        511.99033052, 1169.56742154,  667.95663988, 1037.43971435,
        602.36825113,  458.88971766, 1050.02112264, 1158.66193951,
        381.40591701,  735.82991534, 1054.22344746, 1137.93142842,
       1194.64163105,  529.34543343, 1073.36555413, 1042.80515608,
        453.89444055,  706.93145548,  555.35572183, 1068.9311161 ,
        604.10072755,  405.57567987, 1063.3557614 ,  672.07167471,
        586.91543516,  508.36158156,  493.80925719,  693.42463793,
        524.47165286,  600.02196326])

In [70]:
r2_score(y_test, y_pred)

0.6713572078351764

In [71]:
clf = LogisticRegression()
clf.fit(x_train, y_train)

/Users/kotubhaskarrao/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [72]:
y_pred = clf.predict(x_test)

In [73]:
y_pred

array([ 495, 1045,  840,  750,  560,  750,  495,  660,  750,  830,  495,
        495,  845,  920,  750,  365,  466,  680, 1060,  830,  625,  740,
        520,  380,  520,  750,  718, 1045,  680,  515, 1045, 1045,  630,
        470,  830,  750, 1547,  520, 1045,  620,  625,  695,  630, 1280,
        495,  415, 1035,  830,  675,  406,  630,  750,  520,  345])

In [74]:
accuracy_score(y_pred, y_test)


0.0

In [75]:
confusion_matrix(y_pred, y_test)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [76]:
r2_score(y_, y_pred)

0.3802892026258664