In [1]:
import numpy as np
import pandas as pd

In [2]:
num_list = [1,2,3,4,5,6]
type(num_list)

list

## Create and reshape a numpy array

In [3]:
data = np.array(num_list)
data

array([1, 2, 3, 4, 5, 6])

In [5]:
data.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [6]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Create a numpy array filled with zeors

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Create a dataframe using 1D list and 2D list

In [15]:
pd.DataFrame([1,2,3,4,5])

0
0  1
1  2
2  3
3  4
4  5

In [18]:
pd.DataFrame([[1,2,3,4,5], [6,7,8,9, 10]])

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

## Create a dataframe using a dictionary

In [21]:
data = {
    "fruits": ["banana", "oranges", "guava", "Grapes"],
    "vegetables": ["cucumber", "carrot", "onions", "Potato"]
}

pd.DataFrame(data)

fruits vegetables
0   banana   cucumber
1  oranges     carrot
2    guava     onions
3   Grapes     Potato