***Numpy Handson -1***

In [2]:
# BASICS OF NUMPY -
''' Numpy stands for Numerical Python -
It is a python library used for performing numerical operations
Created in year 2005 by Travis Oliphant why he created ?
Bceause Numpy is upto 50x more faster than list to work with arrays'''

# How to import numpy

import numpy as np

In [3]:
# HOW TO CREATE A NUMPY ARRAY

arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [4]:
array=[1,2,3,4,5]
arr2=np.array(array)
print(arr2)

[1 2 3 4 5]


In [ ]:
# How to create a numpy array of 0 dimensional to 4th dimensional

In [12]:
# Od array

arr1=np.array(22)
print(arr1)
print(arr1.ndim)

22
0


In [6]:
# 1d array

arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [13]:
# 2d array

arr2=np.array([ [1,2,3],[4,5,6]  ])
print(arr2)
print(arr2.ndim)
print(arr2.shape) # output will be in the format of tuple (rows*column)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [14]:
# 3d array
arr3=np.array( [[ [1,2,3],[4,5,6]],[[7,8,9],[10,11,12] ]] )
print(arr3)
print(arr3.shape)  # ( no of 2d array ,rows , column)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [17]:
# 4d array
arr4=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
print(arr4)
print(arr4.ndim)
print(arr4.shape) # ( no of layers , no of 2d array you are using inside your layer , rows , column)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
4
(2, 2, 2, 3)


In [18]:
# indexing

arr1=np.array([1,2,3,4,5])
# i want to access 4
print(arr1[3])

4


In [21]:
# Acces element in 2d array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

# how you will access 9
print(arr2[1,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
9


In [23]:
# how you will access the element in 3d array
arr3=np.array( [[ [1,2,3],[4,5,6]],[[7,8,9],[10,11,12] ]])
print(arr3)
print(arr3.shape)

# i want to acceess 8

print(arr3[ 1, 0 ,1 ]) #( no of 2d array , row no , index)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
8


In [27]:
# access element in 2d array using -ve indexing

arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
# i want to access 7 using -ve indexing

print(arr2[-1,-4])   #( +ve row number or -ve row number , -ve index number)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7


In [32]:
# Slicing in numpy array

# slicing of 1d array
arr1=np.array([1,2,3,4,5])
print(arr1[ 2:4 ])  #( start index , 1 more than ending index)

print(arr1[1:])
print(arr1[ :2])

[3 4]
[2 3 4 5]
[1 2]


In [38]:
# data type of numpy array
arr1=np.array([1,2,3,4,5])
print(arr1.dtype)

arr2=np.array(['apple','banana','orange'])
print(arr2.dtype)
# U6 is the string data  type

# Type casting
arr4=np.array([1,2,3,4,5],dtype='S')
print(arr4)

int64
<U6
[b'1' b'2' b'3' b'4' b'5']


In [45]:
# can i reshape my array

arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])  # 1d array
print(arr1)
print(arr1.shape)
# convert 1 d array to 2d array 3*3
newarr=arr1.reshape(2,6)
print(newarr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [52]:
# convert 2d array  to 3d array

arr5=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
# 2d array to 3d array
newarray=arr5.reshape(2,2,3)
print(newarray)
print(newarray.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


 ***HANDS-ON starts from here -**

In [54]:
'''1. Create a numpy array with numpy.array module and with a data type integer and float'''
import numpy as np

arr1=np.array([1,2,3,4,5],dtype='int')
print(arr1)
print(arr1.dtype)

arr2=np.array([1,2,3,4,5],dtype='float')
print(arr2)
print(arr2.dtype)


[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64


In [ ]:
'''2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
Also, print the shape and dimensions of the numpy arrays created above.
'''
# Already did

In [59]:
'''3. Create a 2x3, 3x3, and 4x4 identity matrix using numpy.'''
arr2=np.identity(2,dtype='int')
print(arr2)

arr3=np.identity(3,dtype='int')
print(arr3)

arr4=np.identity(4,dtype='int')
print(arr4)

# create indentity matrix of 2,3
arrnew=np.eye(2,3,dtype='int')
print(arrnew)


[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0]
 [0 1 0]]


In [63]:
'''4. Create a numpy array with shape 2x5 that has all the elements as zero.'''

arr=np.zeros((2,5),dtype='int')   # 1st way
print(arr)

arr2=np.eye(2,5,dtype='int')  # 2nd way
print(arr2*0)


[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [75]:
'''5. Create a numpy array that has the shape 3x5 and all the elements are 5.'''
# 1st way  of ishita
arr=np.zeros((3,5),dtype='int')
print(arr+5)

# 2nd way
arr2=np.full((3,5),5,dtype='int')  # first paramater is size , second is the number
print(arr2)

# 3rd way
arr3=np.ones((3,5),dtype='int')
print(arr3*5)

# 4th way
arr4=np.eye(3,5,dtype='int')
print(arr4*0+5)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [83]:
'''6. Create a numpy array with random integers in the range 0-100, and the sample size
should be 25.
'''
arr1=np.random.randint(0,101,size=(5,5))  # ( start range , end range+1 , sample size)
print(arr1)

[[95 57 13 16  0]
 [64 19  9 43 55]
 [92 19 53 21 34]
 [80 32 11  3 84]
 [62 32 84 20  5]]


In [88]:
'''7. Create a numpy array with a shape 3x3 that has all elements as 1.'''
arr=np.ones((3,3),dtype='int')
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [92]:
'''8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
Reshape the array in the shape 3x2 and print the updated shape of the resultant array.
'''
arr=np.random.randint(0, 101, size=(2, 3))
print(arr)
newarr=arr.reshape(3,2)
print(newarr)

[[13  5 12]
 [ 2 74 29]]
[[13  5]
 [12  2]
 [74 29]]


In [102]:
'''9.
Step-1 Create a random array, with the range 0-1000, with a size 50 and
step 2. Perform the following operations on the same.
a. Print the first ten elements of the array.
b. Print the last ten elements of the array
c. Print the elements from the indexes 10-25
d. Print the element at the index 22
e. Print the array using negative indexing.
f. Print the last ten elements of the array, using negative indexing.'''

arr1=np.random.randint(0,1001,50)
print(arr1)

# a. Print the first ten elements of the array.
print(arr1[ :10])

#b. Print the last ten elements of the array
print(arr1[40:])

# c. Print the elements from the indexes 10-25
print(arr1[10:26])

# d. Print the element at the index 22
print(arr1[22])

# e. Print the array using negative indexing
print(arr1[: : -1])
print(arr1[-50:])

#f. Print the last ten elements of the array, using negative indexing.'''
print(arr1[-1:-11:-1])



[930 498 363 316 746 540 949 630   3  47 581 646  86 586 603 137  56 923
 447 188 150 805 270 593 125 465 558 182 323 843 755 390 756 181 469 891
 203 738 606 645 561 927 293 821 535 817 349 767  91 147]
[930 498 363 316 746 540 949 630   3  47]
[561 927 293 821 535 817 349 767  91 147]
[581 646  86 586 603 137  56 923 447 188 150 805 270 593 125 465]
270
[147  91 767 349 817 535 821 293 927 561 645 606 738 203 891 469 181 756
 390 755 843 323 182 558 465 125 593 270 805 150 188 447 923  56 137 603
 586  86 646 581  47   3 630 949 540 746 316 363 498 930]
[930 498 363 316 746 540 949 630   3  47 581 646  86 586 603 137  56 923
 447 188 150 805 270 593 125 465 558 182 323 843 755 390 756 181 469 891
 203 738 606 645 561 927 293 821 535 817 349 767  91 147]
[147  91 767 349 817 535 821 293 927 561]


In [123]:
'''10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
a. Insert the element 6 at the end of the array.
b. Insert the element 10 at the beginning of the array.
c. Insert the element 30, before 4 index.
d. Update the element 5 as 50.
e. Delete the element 50 in the updated array.
f. Create a function to search for the element 30.
g. Sort the array in ascending order'''

data= [1,2,3,4,5]
arr=np.array(data)

#a. Insert the element 6 at the end of the array and store it to new array.
newarr=np.append(arr,6)

#b-Insert the element 10 at the beginning of the array
newarr=np.insert(newarr,0,10)

#c. Insert the element 30, before the index 4. ( at 3rd index)
newarr=np.insert(newarr,3,30)

#d. Update the element 5 as 50.
newarr[6]=50

print(newarr)

# np.where(newarr == 5, 50, newarr)

# You can update single value to multiple places
# newarr[4:7]=50       # updated the value 50 from index 4 to index 6
# print(newarr)

# e. Delete the element 50 in the updated array.
newarr2=np.delete(newarr,6)
print(newarr2)

#f. Create a function to search for the element 30.

def search(newarr2,ele):
  if ele in newarr2:
    print("present")
  else:
    print("Not present")

# calling the function
search(newarr2,3)



[10  1  2 30  3  4 50  6]
[10  1  2 30  3  4  6]
present


In [137]:
# Where function

def search(newarr,elementtosearch):
  index=np.where(newarr==elementtosearch) # it will search for index and then store the answer in index variable
  if len(index[0])>0:
    print("element is present at position :",index[0])
  else:
    print("element in not present")

data=[1,2,3,4,5,6,7,8,9,11,34,656,35,234,244,5,355,2233,5,8]
newarr=np.array(data)
elementtosearch=8
search(newarr,elementtosearch)

element is present at position : [ 7 19]


In [139]:
#g. Sort the array in ascending order'''
data=[1,2,3,4,5,6,7,8,9,11,34,656,35,234,244,5,355,2233,5,8]
newarr=np.array(data)
print(newarr)

newarr.sort() # using .sort predefined function
print(newarr)


[   1    2    3    4    5    6    7    8    9   11   34  656   35  234
  244    5  355 2233    5    8]
[   1    2    3    4    5    5    5    6    7    8    8    9   11   34
   35  234  244  355  656 2233]
